# SET THIS CUSTOM TO YOUR ORGANIZATION'S REPOS
ORG_REPOS = []

# REPLY TO ORIGINAL THREAD WHEN ADDED TO QUEUE
SHOULD_SEND_ADD_QUEUE_MESSAGE = False

# WHEN CLICKING "COMPLETE" IN QUEUE, BLOCK MORPHS INTO TEXT SAYING IT HAS BEEN COMPLETED
SHOULD_SHOW_COMPLETED_TEXT = False

# THESE REACTIONS TO MESSAGES CONTAINING PR LINKS WILL BE READ AND RESPECTIVE LINKS WILL BE REMOVED FROM THE QUEUE
LIST_COMPLETE_REACTIONS = ["white_check_mark", "heavy_check_mark"]